-- ===========================================
-- AISKUALERTS DATABASE SCHEMA
-- ===========================================
-- This file is AUTO-GENERATED by dbmate after running migrations.
-- DO NOT EDIT THIS FILE MANUALLY.
-- Run `dbmate up && dbmate dump` to regenerate.
-- ===========================================

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- ===========================================
-- TENANTS (Bsale accounts)
-- ===========================================
CREATE TABLE public.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bsale_client_code TEXT UNIQUE,            -- RUT (Chile), RUC (Peru), RFC (Mexico) - NULL if not connected
    bsale_client_name TEXT,                   -- NULL if not connected to Bsale
    bsale_access_token TEXT,                  -- Encrypted at rest - NULL if not connected
    sync_status TEXT DEFAULT 'not_connected', -- not_connected | pending | syncing | success | failed
    last_sync_at TIMESTAMPTZ,
    -- Billing (provider-agnostic)
    subscription_id TEXT UNIQUE,
    subscription_status TEXT DEFAULT 'none',
    subscription_ends_at TIMESTAMPTZ,
    owner_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- USERS (belong to a tenant)
-- ===========================================
CREATE TABLE public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    name TEXT,
    notification_enabled BOOLEAN DEFAULT true,
    notification_email TEXT,                  -- Override email for notifications
    digest_frequency TEXT DEFAULT 'daily' CHECK (digest_frequency IN ('daily', 'weekly', 'none')),
    subscription_id TEXT UNIQUE,
    subscription_status TEXT DEFAULT 'none' CHECK (subscription_status IN ('none', 'active', 'cancelled', 'past_due')),
    subscription_ends_at TIMESTAMPTZ,
    last_tenant_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, email)
);

-- ===========================================
-- USER_TENANTS (junction table for multi-tenant users)
-- ===========================================
CREATE TABLE public.user_tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    tenant_id UUID NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'member',
    notification_enabled BOOLEAN NOT NULL DEFAULT true,
    notification_email VARCHAR(255),
    digest_frequency VARCHAR(50) NOT NULL DEFAULT 'daily',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, tenant_id)
);

-- ===========================================
-- STOCK SNAPSHOTS (daily sync from Bsale)
-- ===========================================
CREATE TABLE public.stock_snapshots (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    bsale_variant_id INTEGER NOT NULL,
    bsale_office_id INTEGER,                  -- NULL if single location
    sku TEXT,
    barcode TEXT,
    product_name TEXT,
    quantity INTEGER NOT NULL,                -- Physical quantity
    quantity_reserved INTEGER DEFAULT 0,      -- Reserved in pending docs
    quantity_available INTEGER NOT NULL,      -- Available for sale
    unit_price DECIMAL(12, 2) DEFAULT NULL,   -- Price from Bsale
    snapshot_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, bsale_variant_id, bsale_office_id, snapshot_date)
);

-- ===========================================
-- DAILY CONSUMPTION (velocity tracking)
-- ===========================================
CREATE TABLE public.daily_consumption (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    bsale_variant_id INTEGER NOT NULL,
    bsale_office_id INTEGER,
    consumption_date DATE NOT NULL,
    quantity_sold INTEGER NOT NULL DEFAULT 0,
    document_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (tenant_id, bsale_variant_id, bsale_office_id, consumption_date)
);

-- ===========================================
-- THRESHOLDS (user-defined alert triggers)
-- ===========================================
CREATE TABLE public.thresholds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    bsale_variant_id INTEGER,                 -- NULL = default for all SKUs
    bsale_office_id INTEGER,                  -- NULL = all locations
    threshold_type TEXT NOT NULL DEFAULT 'quantity' CHECK (threshold_type IN ('quantity', 'days')),
    min_quantity INTEGER,                     -- Alert when stock <= this (for quantity-based)
    min_days INTEGER,                         -- Alert when days of stock <= this (for days-based)
    days_warning INTEGER DEFAULT 7,           -- Alert when days-to-stockout <= this
    created_by UUID,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, bsale_variant_id, bsale_office_id),
    CONSTRAINT check_threshold_type_fields CHECK (
        (threshold_type = 'quantity' AND min_quantity IS NOT NULL) OR
        (threshold_type = 'days' AND min_days IS NOT NULL)
    )
);

-- ===========================================
-- ALERTS (generated alerts awaiting/sent)
-- ===========================================
CREATE TABLE public.alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    bsale_variant_id INTEGER NOT NULL,
    bsale_office_id INTEGER,
    sku TEXT,
    product_name TEXT,
    alert_type TEXT NOT NULL,                 -- 'threshold_breach' | 'low_velocity'
    current_quantity INTEGER NOT NULL,
    threshold_quantity INTEGER,               -- For threshold_breach type
    days_to_stockout INTEGER,                 -- For low_velocity type
    status TEXT DEFAULT 'pending',            -- pending | sent | dismissed
    sent_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ,                 -- When user dismissed this alert (took action)
    last_notified_at TIMESTAMPTZ,             -- Last time user was emailed about this alert
    dismissed_by UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- SESSIONS (cookie-based auth)
-- ===========================================
CREATE TABLE public.sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    current_tenant_id UUID,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- MAGIC LINK TOKENS (passwordless auth)
-- ===========================================
CREATE TABLE public.magic_link_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    token TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===========================================
-- SCHEMA MIGRATIONS (dbmate tracking)
-- ===========================================
CREATE TABLE public.schema_migrations (
    version VARCHAR(255) PRIMARY KEY
);

-- ===========================================
-- INDEXES
-- ===========================================
CREATE INDEX idx_snapshots_tenant_date ON public.stock_snapshots(tenant_id, snapshot_date DESC);
CREATE INDEX idx_snapshots_variant ON public.stock_snapshots(tenant_id, bsale_variant_id, snapshot_date DESC);
CREATE INDEX idx_consumption_tenant_variant_date ON public.daily_consumption(tenant_id, bsale_variant_id, consumption_date DESC);
CREATE INDEX idx_consumption_date_range ON public.daily_consumption(tenant_id, consumption_date DESC);
CREATE INDEX idx_thresholds_user ON public.thresholds(user_id);
CREATE INDEX idx_thresholds_tenant_variant ON public.thresholds(tenant_id, bsale_variant_id);
CREATE INDEX idx_alerts_user_status ON public.alerts(user_id, status);
CREATE INDEX idx_alerts_tenant_date ON public.alerts(tenant_id, created_at DESC);
CREATE INDEX idx_alerts_dismissed ON public.alerts(tenant_id, bsale_variant_id, status) WHERE status = 'dismissed';
CREATE INDEX idx_sessions_token ON public.sessions(token);
CREATE INDEX idx_sessions_expires ON public.sessions(expires_at);
CREATE INDEX idx_tenants_subscription ON public.tenants(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX idx_users_subscription ON public.users(subscription_id) WHERE subscription_id IS NOT NULL;
CREATE INDEX idx_magic_link_tokens_token ON public.magic_link_tokens(token) WHERE used_at IS NULL;
CREATE INDEX idx_magic_link_tokens_email_created ON public.magic_link_tokens(email, created_at DESC);
CREATE INDEX idx_user_tenants_user ON public.user_tenants(user_id);
CREATE INDEX idx_user_tenants_tenant ON public.user_tenants(tenant_id);

-- ===========================================
-- FOREIGN KEY CONSTRAINTS
-- ===========================================
ALTER TABLE public.user_tenants ADD CONSTRAINT fk_user_tenants_user
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_tenants ADD CONSTRAINT fk_user_tenants_tenant
    FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;
ALTER TABLE public.tenants ADD CONSTRAINT fk_tenants_owner
    FOREIGN KEY (owner_id) REFERENCES public.users(id);
ALTER TABLE public.users ADD CONSTRAINT fk_users_last_tenant
    FOREIGN KEY (last_tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL;
ALTER TABLE public.sessions ADD CONSTRAINT fk_sessions_current_tenant
    FOREIGN KEY (current_tenant_id) REFERENCES public.tenants(id) ON DELETE SET NULL;
ALTER TABLE public.thresholds ADD CONSTRAINT fk_thresholds_created_by
    FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.alerts ADD CONSTRAINT fk_alerts_dismissed_by
    FOREIGN KEY (dismissed_by) REFERENCES public.users(id) ON DELETE SET NULL;

-- ===========================================
-- COLUMN COMMENTS
-- ===========================================
COMMENT ON COLUMN public.users.digest_frequency IS 'Email digest frequency: daily, weekly, or none';
COMMENT ON COLUMN public.thresholds.threshold_type IS 'Type of threshold: quantity (min units) or days (min days of stock)';
COMMENT ON COLUMN public.thresholds.min_days IS 'Minimum days of stock remaining before alert (for days-based thresholds)';
COMMENT ON COLUMN public.daily_consumption IS 'Daily sales quantities per variant, aggregated from Bsale documents';
COMMENT ON COLUMN public.alerts.dismissed_at IS 'When user dismissed this alert (took action)';
COMMENT ON COLUMN public.alerts.last_notified_at IS 'Last time user was emailed about this alert';

-- ===========================================
-- MIGRATION TRACKING DATA
-- ===========================================
-- This data ensures fresh databases are marked with all applied migrations
INSERT INTO public.schema_migrations (version) VALUES
    ('20240101000001'),
    ('20240115000002'),
    ('20240201000003'),
    ('20240215000004'),
    ('20240301000005'),
    ('20240315000006'),
    ('20240401000007'),
    ('20240415000008'),
    ('20240501000009'),
    ('20240515000010'),
    ('20240601000011');
